# Generated by Django 5.1.7 on 2025-04-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_no",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
