# Generated by Django 5.1.7 on 2025-04-24 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_phone_no_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrwal', 'Withdrawal')], max_length=20)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.budget')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
