# Generated by Django 5.1.7 on 2025-04-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
